language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.*' ]]; then pip install --use-mirrors parsedatetime; fi

script:
  - nosetests -v -w /tmp rateestimate.tests
